Develop
Di-52/SimpleNews pull request #1
Opened 2023-02-18 22:09 UTC by Di-52

2023-03-09 12:31 UTC, tim-teacher requested changes
Все через чур сложно сделано. Невероятное количество маперов, вложенности в классах, мапперы в модели интрфейса явно лишние.

2023-03-09 12:31 UTC, tim-teacher commented on src/main/kotlin/Temp.kt
> +
Очень много лишних файлов, которых в гите не должно быть.

2023-03-09 12:31 UTC, tim-teacher commented on src/main/kotlin/data/CloudService.kt
> +    class OkHttpService(private val responseUrl: String) : CloudService {
Лучше не смешивать интерфейс и реализацию в одном файле.

2023-03-09 12:31 UTC, tim-teacher commented on src/main/kotlin/data/DataSource.kt
> +    interface Mutable :DataSource {
Тоже самое тут, лучше сделать отдельными файлами.

2023-03-09 12:31 UTC, tim-teacher commented on src/main/kotlin/data/ResultDataToDomainMapper.kt
> +            return if (result.haveNoNews())
Это уже логика, это можно до мапов сделать, в самом мапе ничего кроме мапинга быть не должно. Также нужно учесть, что если новостей нет это не значит что это ошибка, возможно просто сейчас нет новостей).

2023-03-09 12:31 UTC, tim-teacher commented on src/main/kotlin/data/models/NewsItemData.kt
> +        class ToDomain : Mapper<NewsItemDomain> {
Не сильно вижу смысла в интерфейсах для мапперов тут, по мне так только усложняет все сильно.

2023-03-09 12:31 UTC, tim-teacher commented on src/main/kotlin/data/models/NewsListData.kt
> +    interface Mapper<T> {
И еще, маперы физически убираем из моделей, они должны лежать в разных файлах.

2023-03-09 12:31 UTC, tim-teacher commented on src/main/kotlin/domain/SpecialNewsUseCase.kt
> +    fun keyword(key: String)
Один юз кейс на одну функцию, смешивать не нужно.

2023-03-09 12:31 UTC, tim-teacher commented on src/main/kotlin/domain/UsualNewsUseCase.kt
> +interface UsualNewsUseCase {
Название юз кейсов лучше начинать с глагола.

2023-03-09 15:05 UTC, Di-52 commented on src/main/kotlin/Temp.kt
> +
Да, посмотрел видео разбора, понял, исправлю

2023-03-09 15:08 UTC, Di-52 commented on src/main/kotlin/data/models/NewsItemData.kt
> +        class ToDomain : Mapper<NewsItemDomain> {
Хм... тогда в тестах придется использовать реальные мапперы, и я не смогу протестить как класс работатет с ними...

2023-03-09 15:10 UTC, Di-52 commented on src/main/kotlin/data/models/NewsListData.kt
> +    interface Mapper<T> {
По поводу разных файлов: казалось так получится более удобочитаемый код. Понял - исправлю

2023-03-09 20:25 UTC, Di-52 commented on src/main/kotlin/domain/SpecialNewsUseCase.kt
> +    fun keyword(key: String)
Как тогда лучше между юз кейсами передавать информацию?
Объединить их интерактором?

2023-03-09 20:28 UTC, Di-52 commented on src/main/kotlin/data/CloudService.kt
> +    class OkHttpService(private val responseUrl: String) : CloudService {
Понял

2023-03-09 20:28 UTC, Di-52 commented on src/main/kotlin/data/DataSource.kt
> +    interface Mutable :DataSource {
Понял

2023-03-09 20:30 UTC, Di-52 commented on src/main/kotlin/data/ResultDataToDomainMapper.kt
> +            return if (result.haveNoNews())
Понял

2023-03-09 20:31 UTC, Di-52 commented on src/main/kotlin/domain/UsualNewsUseCase.kt
> +interface UsualNewsUseCase {
GetUsualNewsUseCase ?

2023-03-10 06:13 UTC, Di-52 commented
**Все через чур сложно сделано. Невероятное количество маперов,** 
Пытался максимально ООПшно и СОЛИДно сделать...
**вложенности в классах,** 
имеете ввиду NewsItem в NewsList? или что-то другое?
**мапперы в модели интрфейса явно лишние.**
не понял о чем речь.

2023-03-10 09:21 UTC, tim-teacher commented on src/main/kotlin/data/models/NewsItemData.kt
> +        class ToDomain : Mapper<NewsItemDomain> {
не обязательно, можно просто библиотеку для моков использовать

2023-03-10 09:22 UTC, tim-teacher commented on src/main/kotlin/domain/SpecialNewsUseCase.kt
> +    fun keyword(key: String)
Желательно что бы юз кейсы не общались между собой, это сильно все усложняет, общую логику можно вынести в какие то отдельные классы. Но я если честно не сильно понимаю откуда в таком простом задание может это понадобиться)

2023-03-10 09:22 UTC, tim-teacher commented on src/main/kotlin/domain/UsualNewsUseCase.kt
> +interface UsualNewsUseCase {
Ага

2024-01-11 09:36 UTC, merged