Tests
Di-52/SimpleNews pull request #2
Opened 2023-02-23 11:49 UTC by Di-52

Написал несколько тестов и внес небольшие правки.

2023-03-09 12:44 UTC, tim-teacher requested changes
Сложновато все но это из за кода в приложении. По хорошоме лучше конечно использовать одну из библиотека для мока данных, тогда было бы намного меньше кода.

2023-03-09 12:44 UTC, tim-teacher commented on src/test/kotlin/data/BaseNewsRepositoryTest.kt
> +        actual = repository.fetchNews()
А зачем второй раз вызывать `fetchNews()`? На один тест всегда проверяем только одну функциональность.

2023-03-09 15:02 UTC, Di-52 commented on src/test/kotlin/data/BaseNewsRepositoryTest.kt
> +        actual = repository.fetchNews()
Тут проверяется логика работы: при первом запросе в репозиторий кэш пустой, репозиторий берет новости с сервера и сохраняет в кэш, при повторном запросе - берет из кэша и к серверу не обращается.

2023-03-10 06:18 UTC, Di-52 commented
> Сложновато все но это из за кода в приложении. По хорошоме лучше конечно использовать одну из библиотека для мока данных, тогда было бы намного меньше кода.

Не стал использовать библиотеку, потому как раньше не использовал и побоялся закопаться просто на этом, по той же причине отказался от DI...

2023-03-10 09:24 UTC, tim-teacher commented on src/test/kotlin/data/BaseNewsRepositoryTest.kt
> +        actual = repository.fetchNews()
ну так это два разных кейса, сначала проверяй что бы новости взялись с сервера, затем отдельно проверяй что бы новости брались из кеша.

2024-01-12 13:39 UTC, merged